name: Rust

on:
  push:
    branches: [ "main" ]https://github.com/longmen2022/Deploy_Rust_application_to_AWS_EC2/tree/main
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
